#!/bin/bash

# TrustChain LTO - Cleanup Script for DigitalOcean Deployment
# Removes unnecessary files for production deployment

set -e

echo "🧹 TrustChain LTO - Deployment Cleanup"
echo "========================================"
echo ""
echo "This script will remove files unnecessary for DigitalOcean deployment."
echo "Files will be moved to 'archive/' directory for safety."
echo ""

# Create archive directory
ARCHIVE_DIR="archive"
mkdir -p "$ARCHIVE_DIR"

# Function to archive file
archive_file() {
    local file="$1"
    if [ -e "$file" ]; then
        echo "📦 Archiving: $file"
        mkdir -p "$ARCHIVE_DIR/$(dirname "$file")"
        mv "$file" "$ARCHIVE_DIR/$file" 2>/dev/null || true
    fi
}

# Function to archive directory
archive_dir() {
    local dir="$1"
    if [ -d "$dir" ]; then
        echo "📦 Archiving directory: $dir"
        mkdir -p "$ARCHIVE_DIR"
        mv "$dir" "$ARCHIVE_DIR/$dir" 2>/dev/null || true
    fi
}

echo "Step 1: Archiving unnecessary Docker Compose files..."
archive_file "docker-compose.core.yml"
archive_file "docker-compose.fabric-simple.yml"
archive_file "docker-compose.fabric.yml"
archive_file "docker-compose.laptop.yml"
archive_file "docker-compose.production-no-ipfs.yml"
archive_file "docker-compose.production.yml"
archive_file "docker-compose.services.yml"
archive_file "docker-compose.simple.yml"

echo ""
echo "Step 2: Archiving development Dockerfile..."
archive_file "Dockerfile.laptop"

echo ""
echo "Step 3: Archiving PowerShell scripts (not needed on Linux)..."
archive_file "start-laptop.ps1"
archive_file "start-production.ps1"
archive_file "start-real-services.ps1"
archive_file "scripts/backup-laptop.ps1"
archive_file "scripts/complete-fabric-setup.ps1"
archive_file "scripts/create-channel.ps1"
archive_file "scripts/deploy-chaincode.ps1"
archive_file "scripts/deploy-laptop.ps1"
archive_file "scripts/extract-fabric-components.ps1"
archive_file "scripts/generate-channel-artifacts.ps1"
archive_file "scripts/generate-crypto.ps1"
archive_file "scripts/health-check-laptop.ps1"
archive_file "scripts/setup-fabric-wallet.ps1"
archive_file "scripts/setup-ipfs.ps1"
archive_file "scripts/setup-laptop-fixed.ps1"
archive_file "scripts/setup-postgresql.ps1"
archive_file "scripts/setup-production.ps1"
archive_file "scripts/start-fabric-network.ps1"
archive_file "scripts/upgrade-to-fabric.ps1"

echo ""
echo "Step 4: Archiving one-time fix scripts..."
archive_file "scripts/fix-admin-permissions.sh"
archive_file "scripts/fix-channel-orderer-config.sh"
archive_file "scripts/fix-crypto-permissions.sh"
archive_file "scripts/fix-fabric-access.sh"
archive_file "scripts/fix-fabric-crypto.sh"
archive_file "scripts/fix-ipfs-host.sh"
archive_file "scripts/apply-transfer-schema.sh"
archive_file "scripts/configure-ipfs-real.sh"
archive_file "scripts/redeploy-chaincode.sh"
archive_file "scripts/setup-all-accounts.sh"
archive_file "scripts/setup-tls-certs.sh"
archive_file "scripts/verify-ipfs-connection.sh"
archive_file "scripts/verify-services.sh"
archive_file "scripts/verify-migration.sh"
archive_file "scripts/unified-setup.sh"
archive_file "scripts/setup-simple-fabric.sh"
archive_file "apply-schema-inline.sh"
archive_file "scripts/test-transfer-apis.sh"
archive_file "scripts/cleanup-laptop.js"

echo ""
echo "Step 5: Archiving development/testing files..."
archive_file "scripts/generate-password-hashes.js"
archive_file "scripts/migrate.js"
archive_file "scripts/deploy-chaincode.js"
archive_file "scripts/setup-fabric-wallet.js"
archive_file "scripts/fix-pending-vehicles.sql"

echo ""
echo "Step 6: Archiving development documentation..."
archive_file "ACCOUNT_CREDENTIALS.md"
archive_file "BACKEND_IMPLEMENTATION_SUMMARY.md"
archive_file "CAPSTONE_COMPLIANCE_CHECK.md"
archive_file "CLEANUP_COMPLETED.md"
archive_file "CLEANUP_PHASE2_COMPLETED.md"
archive_file "CLEANUP_REPORT.md"
archive_file "COMPLETE_INTEGRATION_SUMMARY.md"
archive_file "COMPREHENSIVE_WORKSPACE_SUMMARY.md"
archive_file "DOCUMENTATION_AND_SCRIPTS_ANALYSIS.md"
archive_file "ENV_SETUP.md"
archive_file "FABRIC-COMPONENTS-EXTRACTION-GUIDE.md"
archive_file "FABRIC-INTEGRATION-GUIDE.md"
archive_file "FABRIC-PEER-ORDERER-EXPLAINED.md"
archive_file "FREE-VS-PAID-FEATURES.md"
archive_file "FRONTEND_BACKEND_INTEGRATION_PLAN.md"
archive_file "FRONTEND_INTEGRATION_COMPLETE.md"
archive_file "FIX_ADMIN_403_DETAILED.md"
archive_file "FIX_ADMIN_DASHBOARD_403.md"
archive_file "FIX_APPLICATIONS_ISSUE.md"
archive_file "FIX_DASHBOARD_ISSUES.md"
archive_file "HPG_ADMIN_CREDENTIALS.md"
archive_file "HPG_MODULE_SUMMARY.md"
archive_file "HPG_WORKFLOW.md"
archive_file "HYPERLEDGER-FABRIC-COMPONENTS-BREAKDOWN.md"
archive_file "IMPLEMENTATION_PLAN.md"
archive_file "IMPLEMENTATION_STATUS.md"
archive_file "INTEGRATION_STATUS_AND_ACTION_PLAN.md"
archive_file "IPFS-INTEGRATION-GUIDE.md"
archive_file "LAPTOP-SETUP-GUIDE.md"
archive_file "OWNER_CREDENTIALS.md"
archive_file "POSTGRESQL-INTEGRATION-GUIDE.md"
archive_file "POSTGRESQL-QA.md"
archive_file "PROJECT-COMPREHENSIVE-SUMMARY.md"
archive_file "PROJECT-INVENTORY.md"
archive_file "PROJECT_ARCHITECTURE_SUMMARY.md"
archive_file "QUICK_ACCESS.md"
archive_file "QUICK_START.md"
archive_file "QUICK-START-FABRIC.md"
archive_file "QUICK-START-PRODUCTION.md"
archive_file "REAL-SERVICES-SETUP-GUIDE.md"
archive_file "SYSTEM_ARCHITECTURE_AND_GUIDELINES.md"
archive_file "TECHNICAL-IMPLEMENTATION-GUIDE.md"
archive_file "TESTING-GUIDE.md"
archive_file "UI_WORKFLOW_GAP_ANALYSIS.md"
archive_file "UPGRADE-TO-HYPERLEDGER-FABRIC.md"
archive_file "WORKFLOW_IMPLEMENTATION_PLAN.md"

echo ""
echo "Step 7: Archiving development configs..."
archive_file "nginx/laptop.conf"
archive_file "network-config-simple.json"

echo ""
echo "Step 8: Archiving old data directories (optional - will be regenerated)..."
# Commented out by default - uncomment if you want to archive old data
# archive_dir "backup"
# archive_dir "blockchain-ledger"
# archive_dir "logs"
# archive_dir "uploads"
# archive_dir "wallet"

echo ""
echo "✅ Cleanup complete!"
echo ""
echo "📊 Summary:"
echo "  - Files archived to: $ARCHIVE_DIR/"
echo "  - Essential files remain in project root"
echo ""
echo "🔍 Verify essential files exist:"
echo "  - docker-compose.unified.yml"
echo "  - Dockerfile.production"
echo "  - network-config.json"
echo ""
echo "📝 Note: Archive directory can be deleted if not needed, or kept for reference."
echo ""

