#!/bin/bash
# Setup TLS certificates for orderer and peer
# Copies/creates TLS certificates from crypto materials
# PRESERVES SAN certificates generated by cryptogen

set -e

echo "🔐 Setting up TLS certificates..."

# Function to check if certificate has SANs
has_sans() {
    local cert_file=$1
    if [ -f "$cert_file" ]; then
        openssl x509 -in "$cert_file" -text -noout 2>/dev/null | grep -q "Subject Alternative Name" && return 0 || return 1
    fi
    return 1
}

# Orderer TLS setup
ORDERER_TLS_DIR="fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/orderers/orderer.lto.gov.ph/tls"
ORDERER_TLS_CERT="$ORDERER_TLS_DIR/server.crt"
ORDERER_MSP_SIGNCERTS="fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/orderers/orderer.lto.gov.ph/msp/signcerts"
ORDERER_MSP_KEYSTORE="fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/orderers/orderer.lto.gov.ph/msp/keystore"
ORDERER_TLSCA="fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/tlsca"

mkdir -p "$ORDERER_TLS_DIR"

# Check if TLS cert already exists and has SANs
if has_sans "$ORDERER_TLS_CERT"; then
    echo "✅ Orderer TLS certificate already exists with SANs - preserving it"
else
    # Find orderer certificate from MSP
    ORDERER_CERT=$(find "$ORDERER_MSP_SIGNCERTS" -name "*.pem" | head -1)
    ORDERER_KEY=$(find "$ORDERER_MSP_KEYSTORE" -name "*_sk" | head -1)
    ORDERER_TLSCA_CERT=$(find "$ORDERER_TLSCA" -name "*.pem" | head -1)

    if [ -z "$ORDERER_CERT" ] || [ -z "$ORDERER_KEY" ]; then
        echo "❌ Orderer certificates not found"
        exit 1
    fi

    # Copy certificates to TLS directory (only if TLS cert doesn't exist or has no SANs)
    cp "$ORDERER_CERT" "$ORDERER_TLS_DIR/server.crt"
    cp "$ORDERER_KEY" "$ORDERER_TLS_DIR/server.key"

    # Copy TLS CA certificate
    if [ -n "$ORDERER_TLSCA_CERT" ]; then
        cp "$ORDERER_TLSCA_CERT" "$ORDERER_TLS_DIR/ca.crt"
    else
        # Use orderer org CA as fallback
        ORDERER_CA=$(find "fabric-network/crypto-config/ordererOrganizations/lto.gov.ph/msp/cacerts" -name "*.pem" | head -1)
        if [ -n "$ORDERER_CA" ]; then
            cp "$ORDERER_CA" "$ORDERER_TLS_DIR/ca.crt"
        fi
    fi

    echo "✅ Orderer TLS certificates set up (copied from MSP)"
fi

# Peer TLS setup
PEER_TLS_DIR="fabric-network/crypto-config/peerOrganizations/lto.gov.ph/peers/peer0.lto.gov.ph/tls"
PEER_TLS_CERT="$PEER_TLS_DIR/server.crt"
PEER_MSP_SIGNCERTS="fabric-network/crypto-config/peerOrganizations/lto.gov.ph/peers/peer0.lto.gov.ph/msp/signcerts"
PEER_MSP_KEYSTORE="fabric-network/crypto-config/peerOrganizations/lto.gov.ph/peers/peer0.lto.gov.ph/msp/keystore"
PEER_TLSCA="fabric-network/crypto-config/peerOrganizations/lto.gov.ph/tlsca"

mkdir -p "$PEER_TLS_DIR"

# Check if TLS cert already exists and has SANs
if has_sans "$PEER_TLS_CERT"; then
    echo "✅ Peer TLS certificate already exists with SANs - preserving it"
else
    # Find peer certificate from MSP
    PEER_CERT=$(find "$PEER_MSP_SIGNCERTS" -name "*.pem" | head -1)
    PEER_KEY=$(find "$PEER_MSP_KEYSTORE" -name "*_sk" | head -1)
    PEER_TLSCA_CERT=$(find "$PEER_TLSCA" -name "*.pem" | head -1)

    if [ -z "$PEER_CERT" ] || [ -z "$PEER_KEY" ]; then
        echo "❌ Peer certificates not found"
        exit 1
    fi

    # Copy certificates to TLS directory (only if TLS cert doesn't exist or has no SANs)
    cp "$PEER_CERT" "$PEER_TLS_DIR/server.crt"
    cp "$PEER_KEY" "$PEER_TLS_DIR/server.key"

    # Copy TLS CA certificate
    if [ -n "$PEER_TLSCA_CERT" ]; then
        cp "$PEER_TLSCA_CERT" "$PEER_TLS_DIR/ca.crt"
    else
        # Use peer org CA as fallback
        PEER_CA=$(find "fabric-network/crypto-config/peerOrganizations/lto.gov.ph/msp/cacerts" -name "*.pem" | head -1)
        if [ -n "$PEER_CA" ]; then
            cp "$PEER_CA" "$PEER_TLS_DIR/ca.crt"
        fi
    fi

    echo "✅ Peer TLS certificates set up (copied from MSP)"
fi

echo "🎉 TLS certificates setup complete!"

